### ISSUE TITLE
Wrist joint is at elbow

### ISSUE THREAD

**Issue by maluoi** [ultraleap/OpenXRHandTracking#10]
I just checked this with both v4 and the v5 preview installed, the wrist joint appears to be showing up somewhere well down the forearm instead of at the wrist. I'd definitely _love_ to have this forearm information, but perhaps in some other way!

**Comment by rblenkinsopp** [comment]
I'll check this one out shortly, I suspect this is just a mismapping in the OpenXR layer, but I'll confirm this. We are looking at exposing forearm information as well (though this would require an OpenXR Ultraleap vendor extension for now).

**Comment by rblenkinsopp** [comment]
It was just mismapped to the elbow joint (In the OpenXR layer). There is a fix for this now and will be in the next release.
