### ISSUE TITLE
Hand joints in world space?

### ISSUE THREAD

**Issue by korejan** [ultraleap/OpenXRHandTracking#11]
Hi, this isn't specific to leap motion's implementation but I don't know where else would be best to ask this. I just wanted to get some clarification of which coordinate space are the joint poses outputted in for the hand tracking extension, are they all in world space or local space relative to each joint's parent?

From what I've observed and looking at a Microsoft sample they seem to be all in world space but all relative to the palm joint?

When I call xrLocateHandJointsEXT I'm using my app space, space location.

**Comment by rblenkinsopp** [comment]
The hand-joints are all returned in the space that's provided to `xrLocateHandJointsEXT`. The `locateInfo` parameter (2nd parameter is a pointer to a `XrHandJointsLocateInfoEXT` structure, which has the member `baseSpace` which is the `XrSpace` the joints will be returned in.

Your application can therefore request them in world space, view space, or any other space you might care about.

**Comment by korejan** [comment]
> The hand-joints are all returned in the space that's provided to `xrLocateHandJointsEXT`. The `locateInfo` parameter (2nd parameter is a pointer to a `XrHandJointsLocateInfoEXT` structure, which has the member `baseSpace` which is the `XrSpace` the joints will be returned in.
> 
> Your application can therefore request them in world space, view space, or any other space you might care about.

@rblenkinsopp so basically  if you want each hand joint to be in local space, relative to their parents then it's the responsibility of down app/client developer to transform them.

**Comment by rblenkinsopp** [comment]
Yes exactly. You can create your own reference spaces where you want though so you can create a local space at the hand parent location then request the joints relative to that.
