### ISSUE TITLE
Any progress? New release?

### ISSUE THREAD

**Issue by kukel** [ultraleap/OpenXRHandTracking#12]
It's sort of quiet, a year already. 

Thanks for the great product

**Comment by rblenkinsopp** [comment]
Great to hear that you are enjoying the product! :)

You may have seen the recent announcement on our Hand Tracking V5: Gemini Developer Preview (https://www.ultraleap.com/company/news/blog/gemini-v5-preview/). We will be releasing an update to work with this release when the final release is made, along with some other improvements.

If there are specific issues your are running into, or functionality that isn't included that you would like to use, please raise an issue for for any of them and we can look at them in due-course.
