### ISSUE TITLE
API layer does not disable function intercepts when hand-tracking extension is not requested

### ISSUE THREAD

**Issue by rblenkinsopp** [ultraleap/OpenXRHandTracking#14]
This API layer currently does not disable its function intercepts if the `XR_EXT_hand_tracking` extension is *not* requested by the application. This should have no practical effect, as it is undefined behaviour for an application to use these functions in this scenario.

However, this issue can lead to OpenXR conformance test failures when this layer is enabled and should be resolved.

**Comment by Craig-J** [comment]
Fixed in v1.0.0
