### ISSUE TITLE
OpenXR Developer Tool for WMR reports runtime failure

### ISSUE THREAD

**Issue by TomSch71** [ultraleap/OpenXRHandTracking#15]
OpenXR developer tool for windows MR is recommended to check installation of API layer (using version 109.2111.23003.0 on Windows 11) . However, it reports unkown OpenXR runtime, runtime manifest C:\Windows\system32\MixedRealityRuntime.json, exception XrResult failure {XR_ERROR_RUNTIME_FAILURE], origin: xrCreateInstance(&createInfo, instance.Put()).

**Comment by rblenkinsopp** [comment]
Hi @TomSch71, that sounds like an issue with the runtime, rather than something caused by the API layer. However, if you could follow the following steps to diagnose further, that would be appreciated:

- Post a screenshot of the OpenXR developer tool showing the above error message
- Uninstall the Ultraleap OpenXR layer and post another screenshot of the tool
- Reinstall the OpenXR layer and post another screenshot.

If the issue occurs after uninstalling the layer, it is likely an issue with the Windows Mixed Reality runtime that needs to be resolved.

**Comment by TomSch71** [comment]
Hi Robert,

Thank you for your quick response.

I solved the issue just now:

I was triggered by a remark by mbucchia who constructed an additional OpenXR API layer “XR_APILAYER_NOVENDOR_hand_to_controller” ( a layer that in combination with your layer enables basic use of UltraLeap motion in FS2020 via recently released (buggy) controller functionality). He mentioned that it was advised to put his installation in a C:\Program Files\ folder. His layer was installed without a problem. Your installation I had put in a D:\UltraLeap\  folder. And yes (!), after re-installing your software in a C:\Program Files\UltraLeap\ folder (your default suggestion in the installer), it worked.
One minor point was this screen after installation:
  ***@***.***

Turned out that this was irrelevant (?) since going back to “home” tab and again to “system status”, all showed up ok.

I re-tested my conclusions once more and one can reproduce this sequence.

So perhaps it is useful to add to your description at Github that installation should really be in a C:\Program Files\ folder and point out that the above error about LIMIT_REACHED is irrelevant.

Once again, thanks for your quick response. I will now explore the various  Ultra Leap Motion possibilities in my flightsimulators.

Kind regards,
Tom



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TomSch71** [comment]
Hi Robert,

Perhaps I should be a bit careful about this latest irrelevant error – all seems ok but I can still not reproduce mbucchia’s results – controllers do not show up. To be continued.

Regards,
Tom

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Tom ***@***.***>
Sent: Tuesday, 7 December 2021 14:59
To: ***@***.***>
Subject: RE: [ultraleap/OpenXRHandTracking] OpenXR Developer Tool for WMR reports runtime failure (Issue #15)

Hi Robert,

Thank you for your quick response.

I solved the issue just now:

I was triggered by a remark by mbucchia who constructed an additional OpenXR API layer “XR_APILAYER_NOVENDOR_hand_to_controller” ( a layer that in combination with your layer enables basic use of UltraLeap motion in FS2020 via recently released (buggy) controller functionality). He mentioned that it was advised to put his installation in a C:\Program Files\ folder. His layer was installed without a problem. Your installation I had put in a D:\UltraLeap\  folder. And yes (!), after re-installing your software in a C:\Program Files\UltraLeap\ folder (your default suggestion in the installer), it worked.
One minor point was this screen after installation:
  ***@***.***

Turned out that this was irrelevant (?) since going back to “home” tab and again to “system status”, all showed up ok.

I re-tested my conclusions once more and one can reproduce this sequence.

So perhaps it is useful to add to your description at Github that installation should really be in a C:\Program Files\ folder and point out that the above error about LIMIT_REACHED is irrelevant.

Once again, thanks for your quick response. I will now explore the various  Ultra Leap Motion possibilities in my flightsimulators.

Kind regards,
Tom



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TomSch71** [comment]
Hi Robert,
I can confirm that it all works, controllers do show up. The “irrelevant error” issue remains for me. Each time you start the OpenXR Developer Tool it shows:

***@***.***

However, after waiting +/- 30 seconds it changes into the regular window:

***@***.***

and the API layers show up on the next tab and work.

Seems you can close out the issue.

Regards,
Tom

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Tom ***@***.***>
Sent: Tuesday, 7 December 2021 15:18
To: ***@***.***>
Subject: RE: [ultraleap/OpenXRHandTracking] OpenXR Developer Tool for WMR reports runtime failure (Issue #15)

Hi Robert,

Perhaps I should be a bit careful about this latest irrelevant error – all seems ok but I can still not reproduce mbucchia’s results – controllers do not show up. To be continued.

Regards,
Tom

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Tom ***@***.***>
Sent: Tuesday, 7 December 2021 14:59
To: ***@***.***>
Subject: RE: [ultraleap/OpenXRHandTracking] OpenXR Developer Tool for WMR reports runtime failure (Issue #15)

Hi Robert,

Thank you for your quick response.

I solved the issue just now:

I was triggered by a remark by mbucchia who constructed an additional OpenXR API layer “XR_APILAYER_NOVENDOR_hand_to_controller” ( a layer that in combination with your layer enables basic use of UltraLeap motion in FS2020 via recently released (buggy) controller functionality). He mentioned that it was advised to put his installation in a C:\Program Files\ folder. His layer was installed without a problem. Your installation I had put in a D:\UltraLeap\  folder. And yes (!), after re-installing your software in a C:\Program Files\UltraLeap\ folder (your default suggestion in the installer), it worked.
One minor point was this screen after installation:
  ***@***.***

Turned out that this was irrelevant (?) since going back to “home” tab and again to “system status”, all showed up ok.

I re-tested my conclusions once more and one can reproduce this sequence.

So perhaps it is useful to add to your description at Github that installation should really be in a C:\Program Files\ folder and point out that the above error about LIMIT_REACHED is irrelevant.

Once again, thanks for your quick response. I will now explore the various  Ultra Leap Motion possibilities in my flightsimulators.

Kind regards,
Tom



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by rblenkinsopp** [comment]
Hi Tom, thanks for confirming that you've resolved this. Unfortunately GitHub hasn't dealt well with images via email so I unfortunately can't see any of the image you have posted so I can't help with that remaining error, but if you do post back on the GitHub issue thread (https://github.com/ultraleap/OpenXRHandTracking/issues/15) I can look, but I will mark this issue as closed for now.
