### ISSUE TITLE
I'm trying to adjust the tilts, but there is no instructions on where to put the environment variable.

### ISSUE THREAD

**Issue by 86abaile** [ultraleap/OpenXRHandTracking#16]
I'm trying to adjust the tilts, but there is no instructions on where to put the environment variable.
I know I need to use the code: `ULTRALEAP_OPENXR_TILT_ANGLE` 10 but I don't know where to put it.

**Comment by rblenkinsopp** [comment]
On Windows you can set the through the advanced settings, there is a guide to doing this here: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

**Comment by rblenkinsopp** [comment]
@86abaile Did this resolve your issue?

**Comment by 86abaile** [comment]
Long story short, I don't know. I ended up 3D printing a mount that was level and although the environment variable is still there, the visualizer image lines up with the level mount. I didn't test the tilted mount in the end.

**Comment by rblenkinsopp** [comment]
If you want to test if they are being picked up, you can deliberately set large values (25-degree tilt, or -1m forward) which will mean that you should clearly see the effect. If you have no variables set it will default to assuming the tracker is 80mm forward from your eyes and level (directly forward-facing). Sounds like you have found a workable solution so I will close this ticket for now. Please reopen/comment further if you need further help.
