### ISSUE TITLE
How to use this for MSFS and DCS under OpenXR?

### ISSUE THREAD

**Issue by andyanfieldroad** [ultraleap/OpenXRHandTracking#17]
I am running OpenXR Runtime to play MSFS and DCS.

Will this work for allowing hand tracking with a Leap Motion device on my HP Reverb G2?  So far I have been able to get this to work on MSFS under SteamVR but that is not ideal.

**Comment by rblenkinsopp** [comment]
Hi There, at the moment neither MSFS nor DCS has built-in support for OpenXR hand-tracking, however, for MSFS there is a thread detailing instructions and a tool (when used with this API layer) that allows them to work together:
https://forums.flightsimulator.com/t/hand-tracking-in-msfs-leap-motion-ultraleap-native-support-for-wmr-openxr/475308

Take a look at that thread, and I suggest you ask there if you have any questions, but lots of users have managed to get this working successfully there. I'm happy to help out here with any issues encountered with the layer, and I'm also on that thread if there are any issues.
