### ISSUE TITLE
Increase smoothing

### ISSUE THREAD

**Issue by wheeliemonster** [ultraleap/OpenXRHandTracking#18]
Hi there. Just a quick question from me. Hope that's OK.

When using this in conjunction with MSFS and the OpenXR Toolkit I find that the movements are extremely jittery and sensitive. Is there any way to apply/increase smoothing on the output from this layer prior to it being handed over to the OXR Toolkit layer?

I understand that this will trade off some accuracy/responsiveness, of course.

No worries if not and thanks for this great software :)

**Comment by rblenkinsopp** [comment]
Hi there,There is already some filtering/smoothing that is applied, however, at the moment this is not tunable. This might be something we can look at in future, however, the default levels are normally acceptable, so I'd to understand if something is going wrong in your instance. To help further, is it possible you could provide some more information:

- What tracking device are you using? (LMC / SIR 170 / something else).
- What version of our tracking software are you using (this can be found in the control panel)
- Is it possible that you could record a short video showing your issue? 

Thanks.

**Comment by wheeliemonster** [comment]
Thanks for getting back to me so quickly.
I'm using the latest 5.6.1 on an LMC.

I'm not sure it's an issue as such as the visualiser seems to show good tracking, it was more whether we were able to access any controls in that regard. I suspect your defaults are exactly where they should be.

I think because the OpenXR Toolkit essentially "maps" hands on to (in my case Reverb G2) controllers, they are of course designed differently with the controllers using accelerometers, etc. and the Leap doing whatever magic you do to calculate hand position/orientation! Plus I don't feel like the in-game implementation of the controllers is particularly brilliant anyway :)

I'll see if I can video something to give you an idea, but it might not be particularly quickly forthcoming! Time for such things is limited (working really gets in the way!)

**Comment by wheeliemonster** [comment]
I'm going to close this issue down now. I've not got the time to really put into it, so thank you for taking the time out to reply to me - much appreciated.
