### ISSUE TITLE
Joints are all reported as the same radius

### ISSUE THREAD

**Issue by rblenkinsopp** [ultraleap/OpenXRHandTracking#2]
The same radius is reported for all the joints in the hand. This can lead to odd-looking visualisations of the hand if these radii are used to size finger proxy objects.

This is currently a limitation of the underlying LeapC library which returns the same value for all joints. Possible solutions to this include:

- Enhancing LeapC with finger width support
- Use sensible defaults of the joint widths based on average hand measurements (possibly looked up based on finger length)

**Comment by bjornbytes** [comment]
Ah, oh well.  Thanks for the clarification!

**Comment by maluoi** [comment]
For what it's worth here, I'd love to see some reasonable default joint sizes! I used to provide my own defaults before I switched to the radius provided by OpenXR, and now I don't have a nice way to decide if I should switch back to my own. Since I use this info for generating finger tubes, this can result in some really noodle-y looking fingers :)

**Comment by paulmelis** [comment]
Are there any improvements for more realistic finger joint radii? I've been using StereoKit on a Varjo XR-3 and there the fingers are just way to big, almost unusable. SK directly uses the joint radii provided by OpenXR.

**Comment by rblenkinsopp** [comment]
If you are using OpenXR with a Varjo XR-3, I presume you don't have this API layer installed? The Varjo OpenXR runtime includes built-in support for the `XR_EXT_hand_tracking` extension as such doesn't require this layer to be installed for functional hand-tracking.

Currently, the finger-joint radius is a limitation of the underlying tracking system. I'll pass your feedback onto the team responsible, but we are also planning to look at providing more sensible defaults through this layer in the future.

**Comment by paulmelis** [comment]
> If you are using OpenXR with a Varjo XR-3, I presume you don't have this API layer installed? The Varjo OpenXR runtime includes built-in support for the XR_EXT_hand_tracking extension as such doesn't require this layer to be installed for functional hand-tracking.

@rblenkinsopp I'm mere merely following up the original remarks from StereoKit's developer @maluoi on the hand tracking thickness. I guess StereoKit doesn't directly use this API layer. So would it be better to report this as an OpenXR issue with Varjo directly? 

> Currently, the finger-joint radius is a limitation of the underlying tracking system. I'll pass your feedback onto the team responsible, but we are also planning to look at providing more sensible defaults through this layer in the future.

Any progress would be great. Currently, this is what the finger radius looks like in StereoKit:

![afbeelding](https://user-images.githubusercontent.com/1408287/160349713-ed2b551c-0e7f-4446-8f28-fd0af920af76.png)

**Comment by rblenkinsopp** [comment]
Closing this issue as this GitHub is being archived now the API layer is included as part of the standard Ultraleap Tracking Download. We are working on this on our layer, but if you are only working on top of Varjo, you should report it to them as well so it works with their implementation.
