### ISSUE TITLE
The API Layer does not work with Unreal Engine 4.25

### ISSUE THREAD

**Issue by rblenkinsopp** [ultraleap/OpenXRHandTracking#4]
Enabling the API layer with Unreal Engine 4.25 leads to a number of difficult to diagnose errors. This is due to Unreal 4.25 shipping with version 1.0.0 of the OpenXR loader which has a known issue (https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/91) which prevents OpenXR API layers from functioning correctly. The nature of this bug causing function pointers to have the wrong addresses leads to a number of different error messages which are not indicative of the underlying cause.

This can be demonstrated to be the underlaying causing by replacing the shipped OpenXR Loader DLLs with newer versions (`1.0.1` or greater).

This will be permanently resolved when Unreal Engine ships with a newer OpenXR loader, and should be closed when this is verified.

**Comment by SebastienTussiau** [comment]
Is this issue still there with Unreal 4.26?

**Comment by muchcharles** [comment]
> Is this issue still there with Unreal 4.26?

It ships with 1.0.9 in 4.26 so hopefully not

**Comment by rblenkinsopp** [comment]
Correct, this is resolved in 4.26 and above, I'll close the issue out.
