### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by frostworx** [ultraleap/OpenXRHandTracking#9]
as there's no linux build I wonder if you are working on it?
would be sad if it would die like the orion linux support

**Comment by rblenkinsopp** [comment]
Right now, this release only supports Windows because the current V4 Orion release only supports Windows and this builds on top of it. If that support changes, then this API layer can be extended to support Linux as well.

**Comment by frostworx** [comment]
ic, thanks for the reply!

**Comment by marbetschar** [comment]
+1 from my end for Linux support. Is there anyplace we can follow in order to get notified in case V4 Orion receives Linux support?

**Comment by rblenkinsopp** [comment]
It will be announced at https://www.ultraleap.com/company/news/ when/if it is occurs. We have announced other releases such as the Gemini V5 preview release (https://www.ultraleap.com/company/news/blog/gemini-v5-preview/) here in the past.
